### PR TITLE
allows for different size ring buffers

### PR DESCRIPTION
**Pull request by Ballen7**

### CODE REVIEW

**Comment by Ballen7** [comment]
@AndersKaloer I wanted different size buffers so I made this change. Thought I would share.

**Review by justinpickering — COMMENTED** [review]
this adds a lot of pointer arithmetic overhead. NACK

**Comment by AndersKaloer** [comment]
Thanks @Ballen7, this is certainly a nice feature! I will take a closer look soon.

@justinpickering Is there anything specifically that you are referring to? Sure, it increases the memory footprint by a small amount and adds some instructions, but it is still very lightweight. I think the changes would barely be noticeable unless the application is extremely time critical.

**Comment by Ballen7** [comment]
@justinpickering It would add a couple instructions, acceptable in my opinion. This implementation is already extremely fast due to the use of the buffer mask bit manipulation.

@AndersKaloer Let me know what you think about how I setup the ringbuffer_assert.h, I am not sure if this is the right approach. It might make using the lib less user friendly, an alternative would be to have ring_buffer_init() return a failure and leave it to the application writer to detect that, then we could remove the ringbuffer_assert.h all together.

**Comment by AndersKaloer** [comment]
@Ballen7 I think it is fine to use a custom assert. But I would actually keep it simple and just put
```c
#define RINGBUFFER_ASSERT(x) assert(x)
```
in `ringbuffer.h` instead of having a separate file.

**Comment by Ballen7** [comment]
@AndersKaloer Ok.

**Comment by AndersKaloer** [comment]
Thanks! I made a few minor changes and merged.

**Pull request merged**
